name: Workflow for Java

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print greeting
        run: echo "Hello Java!"

      - name: Print goodbye
        run: echo "Done - see you soon!"