name: Workflow for Java CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Oracle JDK 22
        run: |
          curl -LJO https://download.oracle.com/java/22/latest/jdk-22_linux-x64_bin.tar.gz
          tar -xvzf jdk-22_linux-x64_bin.tar.gz
          sudo mv jdk-22 /opt/jdk-22

      - name: Set up Oracle JDK 22
        run: |
          echo "JAVA_HOME=/opt/jdk-22" >> $GITHUB_ENV
          echo "/opt/jdk-22/bin" >> $GITHUB_PATH

      - name: Verify Java version
        run: java -version

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
