name: Workflow for Java CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Compile Java files
        run: |
          javac src/**/*.java

      - name: Run Main class
        run: |
          java -cp src Main
